

-- Allscripts OBSERVATION_FACT load

SELECT  AD.CLIENTGUID           AS PATIENTID_IDE,
        ALGN.CODE               AS ALLERGY_NAME,
        ALGN.TYPECODE           AS ALLERGY_CLASS,
        ADSL.SVRTYLEVELCODE     AS ALLERGY_REACTION,
        ACM.CONCEPT_CD,
        ARM.MODIFIER_CD,
        AINM.INSTANCE_NUM
FROM    SUNRISE.CV3ALLERGYDECLARATION@CLARITY_AT_EPIC.MI AD
INNER JOIN
        SUNRISE.CV3ALLERGEN@CLARITY_AT_EPIC.MI ALGN
ON      AD.ALLERGENGUID = ALGN.GUID
AND     AD.ACTIVE = 1
INNER JOIN
        ETL.ALLERGY_CONCEPT_MAPPING ACM
ON      ACM.NAME  = UPPER(ALGN.CODE)
AND     ACM.CLASS = UPPER(ALGN.TYPECODE)
LEFT OUTER JOIN
        SUNRISE.CV3ALLERGYDECLSVRTYLEVELXREF@CLARITY_AT_EPIC.MI ADSL
ON      AD.GUID = ADSL.ALLERGYDECLARATIONGUID
LEFT OUTER JOIN
        ETL.ALLERGY_REACT_MAPPING ARM
ON      ADSL.SVRTYLEVELCODE = ARM.NAME
LEFT OUTER JOIN
        ETL.ALLERGY_W_REACT_INST_MAPPING AINM
ON      AINM.ALLERGY_ID = AD.GUID      




-- Epic observatiion fact load

SELECT  ALG.PAT_ID         AS PATIENTID_IDE, 
        ALGD.ALLERGEN_NAME AS ALLERGY_NAME, 
        ZAT.NAME           AS ALLERGY_CLASS,
        ALGR.NAME          AS ALLERGY_REACTION,
        ACM.CONCEPT_CD,
        ARM.MODIFIER_CD
FROM    CLARITY.ALLERGY ALG
INNER JOIN 
        CLARITY.CL_ELG ALGD
ON      ALG.ALLERGEN_ID = ALGD.ALLERGEN_ID
AND     ALG.ALRGY_STATUS_C = 1
INNER JOIN
        CLARITY.ZC_ALLERGEN_TYPE ZAT
ON      ALGD.ALLERGEN_TYPE_C = ZAT.ALLERGEN_TYPE_C
INNER JOIN
        ETL.ALLERGY_CONCEPT_MAPPING ACM
ON      ACM.NAME  = UPPER(ALGD.ALLERGEN_NAME)
AND     ACM.CLASS = UPPER(ZAT.NAME)
LEFT OUTER JOIN 
        CLARITY.ALLERGY_REACTIONS ALGRS
ON      ALG.ALLERGY_ID = ALGRS.ALLERGY_ID
LEFT OUTER JOIN
        CLARITY.ZC_REACTION ALGR
ON      ALGRS.REACTION_C = ALGR.REACTION_C
LEFT OUTER JOIN
        ETL.ALLERGY_REACT_MAPPING ARM
ON      ALGR.NAME = ARM.NAME
;







