DROP TABLE ETL.ALLERGY_W_REACT_INST_MAPPING;

CREATE TABLE ETL.ALLERGY_W_REACT_INST_MAPPING
(
        ALLERGY_ID NUMBER(16) NOT NULL,
        INSTANCE_NUM INTEGER NOT NULL
)
;

INSERT INTO ETL.ALLERGY_W_REACT_INST_MAPPING
SELECT  DISTINCT A.GUID,
        COUNT(*)
FROM    SUNRISE.CV3ALLERGYDECLARATION@CLARITY_AT_EPIC.MI A
INNER JOIN
        SUNRISE.CV3ALLERGYDECLSVRTYLEVELXREF@CLARITY_AT_EPIC.MI b
ON      A.GUID = B.ALLERGYDECLARATIONGUID
GROUP BY A.GUID
HAVING COUNT(*) > 1;
;


INSERT INTO ETL.ALLERGY_W_REACT_INST_MAPPING
SELECT  A.ALLERGY_ID,
        COUNT(*)
FROM    CLARITY.ALLERGY A
INNER JOIN
        CLARITY.ALLERGY_REACTIONS B
ON      A.ALLERGY_ID = B.ALLERGY_ID
GROUP BY A.ALLERGY_ID
HAVING COUNT(*) > 1;

DROP SEQUENCE ETL.ALLERGY_W_REACT_INST_SEQ;

CREATE SEQUENCE ETL.ALLERGY_W_REACT_INST_SEQ;

UPDATE ETL.ALLERGY_W_REACT_INST_MAPPING
SET    INSTANCE_NUM = ETL.ALLERGY_W_REACT_INST_SEQ.NEXTVAL


CREATE INDEX ALLERGY_ID ON ETL.ALLERGY_W_REACT_INST_MAPPING(ALLERGY_ID);