DROP TABLE ETL.ALLERGY_REACT_LIST;
DROP SEQUENCE ETL.ALLERGY_REACT_SEQ


CREATE TABLE ETL.ALLERGY_REACT_MAPPING
(
    NAME        VARCHAR2(100) NOT NULL,
    MODIFIER_CD VARCHAR2(100) NOT NULL
);


CREATE SEQUENCE ETL.ALLERGY_REACT_SEQ;

INSERT INTO ETL.ALLERGY_REACT_MAPPING
SELECT  NAME                    AS NAME,
        'ALLERGEN:REACTION:'    AS MODIFIER_CD
FROM    CLARITY.ZC_REACTION B
UNION
SELECT  DISTINCT SVRTYLEVELCODE AS NAME,
        'ALLERGEN:REACTION:'    AS MODIFIER_CD
FROM    SUNRISE.CV3ALLERGYDECLSVRTYLEVELXREF@CLARITY_AT_EPIC.MI
ORDER BY NAME
;

UPDATE ETL.ALLERGY_REACT_MAPPING
SET    MODIFIER_CD = MODIFIER_CD || ETL.ALLERGY_REACT_SEQ.NEXTVAL