DROP TABLE ETL.ALLERGY_MAPPING;
DROP SEQUENCE ETL.ALLERGY_MAPPING_SEQ;

CREATE TABLE ETL.ALLERGY_MAPPING
(
    NAME       VARCHAR2(200) NOT NULL,
    CLASS      VARCHAR2(100) NOT NULL,
    CONCEPT_CD VARCHAR2(100) NOT NULL
);



INSERT INTO ETL.ALLERGY_MAPPING
SELECT  DISTINCT
        UPPER(B.ALLERGEN_NAME) AS NAME,
        UPPER(C.NAME)          AS CLASS, 
        'UTHSCSA|ALLERGEN|'    AS CONCEPT_CD
FROM    CLARITY.ALLERGY A
INNER   JOIN 
        CLARITY.CL_ELG  B
ON      A.ALLERGEN_ID = B.ALLERGEN_ID
AND     A.ALRGY_STATUS_C = 1
INNER JOIN
        CLARITY.ZC_ALLERGEN_TYPE C
ON      B.ALLERGEN_TYPE_C = C.ALLERGEN_TYPE_C
UNION
SELECT  DISTINCT
        UPPER(B.CODE)     AS NAME, 
        UPPER(B.TYPECODE) AS CLASS,
        'UTHSCSA|ALLERGEN|' AS CONCEPT_CD
FROM    SUNRISE.CV3ALLERGYDECLARATION@CLARITY_AT_EPIC.MI A
INNER JOIN
        SUNRISE.CV3ALLERGEN@CLARITY_AT_EPIC.MI B
ON      A.ALLERGENGUID = B.GUID
AND     A.ACTIVE = 1
;

CREATE SEQUENCE ETL.ALLERGY_MAPPING_SEQ;

UPDATE ETL.ALLERGY_MAPPING
SET    CONCEPT_CD = CONCEPT_CD || ETL.ALLERGY_MAPPING_SEQ.NEXTVAL
;

CREATE INDEX ETL.NAME_CLASS ON ETL.ALLERGY_MAPPING(NAME, CLASS);
