INSERT INTO BLUEHERONMETADATA.CONCEPT_DIMENSION
SELECT C_FULLNAME AS CONCEPT_PATH,
       C_BASECODE AS CONCEPT_CD,
       C_FULLNAME AS NAME_CHAR,
       NULL       AS CONCEPT_BLOB
       SYSDATE    AS UPDATE_DATE
       NULL       AS DOWNLOAD_DATE
       UTHSCSA@UTHSCSA.com AS SOURCESYSTEM_CD
       NULL       AS UPLOAD_ID
FROM   BLUEHERONMETADATA.HERON_TERMS
WHERE  C_BASECODE = 'UTHSCSA|ALLERGEN|%'
ORDER BY C_FULLNAME
;