INSERT INTO BERNOCCHI.CONCEPT_DIMENSION -- BLUEHERONDATA.CONCEPT_DIMENSION
SELECT C_FULLNAME AS CONCEPT_PATH,
       C_BASECODE AS CONCEPT_CD,
       C_FULLNAME AS NAME_CHAR,
       NULL       AS CONCEPT_BLOB,
       SYSDATE    AS UPDATE_DATE,
       NULL       AS DOWNLOAD_DATE,
       NULL       AS IMPORT_DATE,
       'UTHSCSA@UTHSCSA.com' AS SOURCESYSTEM_CD,
       NULL       AS UPLOAD_ID
FROM   BERNOCCHI.HERON_TERMS -- BLUEHERONMETADATA.HERON_TERMS
WHERE  C_BASECODE LIKE 'UTHSCSA|ALLERGEN|%'
;