SELECT  A."ClientGUID",
        C.CONCEPT_CD
FROM    CV3AllergyDeclaration@UHSSUNRISE.MI A
INNER JOIN
        CV3Allergen@UHSSUNRISE.MI B
ON      A."AllergenGUID" = B."GUID"
AND     A."Active" = 1
INNER JOIN
        ETL.ALLERGY_MAPPING C
ON      C.NAME = UPPER(B."Code")
AND     C.CLASS = UPPER(B."TypeCode")




SELECT  A.PAT_ID, D.ALLERGEN_NAME, C.NAME
FROM    clarity.allergy a
INNER JOIN 
        CLARITY.CL_ELG D
ON      A.ALLERGEN_ID = D.ALLERGEN_ID
INNER JOIN 
        CLARITY.ALLERGY_REACTIONS B
ON      A.ALLERGY_ID = B.ALLERGY_ID
INNER JOIN
        clarity.ZC_REACTION C
ON      B.REACTION_C = C.REACTION_C
ORDER BY A.PAT_ID, D.ALLERGEN_NAME, C.NAME
